export const filterData = [
    { name: "FastFood", image: require("../Global/images/burger.jpg"), id: "0" },
    { name: "ChineseFood", image: require("../Global/images/chinesefood.jpg"), id: "1" },
    { name: "NativeFood", image: require("../Global/images/nativefood.jpg"), id: "2" },
    { name: "Pasta", image: require("../Global/images/pasta.jpg"), id: "3" },
    { name: "Salad", image: require("../Global/images/salads.jpg"), id: "4" },
    { name: "SeaFood", image: require("../Global/images/seafood.jpg"), id: "5" },
    { name: "Juice", image: require("../Global/images/fresh_juices.jpeg"), id: "6" },
    { name: "IceCream", image: require("../Global/images/icecream.jpg"), id: "7" },
  ];
  

export const restaurantData = [
{restaurantName:"McDonald's" , farAway:"21.2",
businessAddress:"Johar Town Lahore" , images:'https://content.jdmagicbox.com/comp/mumbai/d3/022pxx22.xx22.160111105945.k3d3/catalogue/mcdonald-s-bandra-west-mumbai-fast-food-1qoza3vssi.jpg?clr=',
averageReview:4.9 , numberofReview:272,coordinates:{lat:-26.1888612 , lng:28.246325},discount:10 , deliveryTime:45 , collectTime:5 , foodType:"Burgers , Fries , Wraps , Shakes",
productData:[{name:"Burger" , price:350 , image:"https://static.independent.co.uk/s3fs-public/thumbnails/image/2019/04/26/09/mcdonalds-bigvegants.jpg?width=1200",productDetails:'Gluten-free, nutrient-rich ancient grain'},
{name:"Wrap" , price:500 , image:"https://desirerecipes.com/wp-content/uploads/2022/09/image-11.jpg",productDetails:'Portable, endless flavor options'},
{name:"Shake" , price:400 , image:"https://dehayf5mhw1h7.cloudfront.net/wp-content/uploads/sites/1282/2023/06/23130414/Mcdonalds.png",productDetails:'Quick, nutritious, post-workout fuel'},
{name:"Fries" , price:120 , image:"https://www.thedailymeal.com/img/gallery/the-mcdonalds-fries-scandal-youve-forgotten-about/l-intro-1658169563.jpg",productDetails:'Golden, salty, irresistible indulgence'},
{name:"ColdDrink" , price:120 , image:"https://pbs.twimg.com/amplify_video_thumb/1215328334432870401/img/X9vqjOmPcaHewuWw.jpg",productDetails:'Quenching thirst with chill delight'},
],
id:0,
category: "FastFood",},



    {restaurantName:"KFC" , farAway:"12.2",
    businessAddress:"Johar Town Lahore" , images:'https://tb-static.uber.com/prod/image-proc/processed_images/dc1fdf93b0ed4cad29b8a4d7c5153488/3ac2b39ad528f8c8c5dc77c59abb683d.jpeg',
    averageReview:4.7 , numberofReview:372,coordinates:{lat:-26.1888612 , lng:28.246325},discount:20, deliveryTime:45 , collectTime:5 , foodType:"Burgers , Fries , Wraps , Shakes , Wings",
    productData:[{name:"Burger" , price:350 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0V1xbMjHP65RR3KYAHaXDvBt9GCo2YGfNvg&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Wrap" , price:600 , image:"https://www.kfc-suisse.ch/fileadmin/_processed_/a/6/csm_mood_wrap_twister_b3d07ff0d6.jpg",productDetails:'Portable, endless flavor options'},
    {name:"Shake" , price:300 , image:"https://i2-prod.mirror.co.uk/incoming/article24300776.ece/ALTERNATES/n615/0_W6_21_GPM_KRU_DELIVERY.jpg",productDetails:'Quick, nutritious, post-workout fuel'},
    {name:"Fries" , price:120 , image:"https://images.deliveryhero.io/image/fd-pk/Products/257946.png?width=%s",productDetails:'Golden, salty, irresistible indulgence'},
    {name:"ColdDrink" , price:120 , image:"https://pbs.twimg.com/amplify_video_thumb/1215328334432870401/img/X9vqjOmPcaHewuWw.jpg",productDetails:'Quenching thirst with chill delight'},
    {name:"Wings" , price:400 , image:"https://media-cdn.tripadvisor.com/media/photo-s/1a/f5/b5/1a/chicken-wings.jpg",productDetails:'Crispy, flavorful, finger-licking satisfaction'},
],
    id:1,
    category:'FastFood'},

    {restaurantName:"Papa Johns" , farAway:"13.2",
    businessAddress:"J50, Block R1" , images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRn1dZpbgSb-VVxqY9yUfUFgha527_8Qzd0XYTKbrgOqGun_u8Zf6vEKLXJkjeAO0VJvHs&usqp=CAU',
    averageReview:4.9 , numberofReview:243,coordinates:{lat:-26.1888612 , lng:28.246325},discount:30 , deliveryTime:25 , collectTime:10 , foodType:"Pizza, Fries , Wraps , Shakes , Wings",
    productData:[{name:"Pizza" , price:1200 , image:"https://hips.hearstapps.com/hmg-prod/images/pj-crispy-20parm-20pizza-pepperoni-1675269016.jpg?crop=1xw:1xh;center,top&resize=1200:*",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Wrap" , price:600 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjL2_x_CEIlFop7DQ3GztNr-hn8GJpnxv4rA&usqp=CAU",productDetails:'Portable, endless flavor options',},
    
    {name:"Fries" , price:120 , image:"https://media-cdn.tripadvisor.com/media/photo-s/04/3a/bb/9d/john-s-lunch.jpg",productDetails:'Golden, salty, irresistible indulgence'},
    {name:"ColdDrink" , price:120 , image:"https://pbs.twimg.com/amplify_video_thumb/1215328334432870401/img/X9vqjOmPcaHewuWw.jpg",productDetails:'Quenching thirst with chill delight'},
    {name:"Wings" , price:400 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT73vmp2FpCHIbRIlDrO9LmNL2gBnsijMaoIA&usqp=CAU",productDetails:'Crispy, flavorful, finger-licking satisfaction'},
],
    id:2,
    category:'FastFood'},

    {restaurantName:"Veera 5" , farAway:"20.2",
    businessAddress:"Building no 80,Street6" , images:'https://www.youlinmagazine.com/articles/1560-3.jpg',
    averageReview:4.6 , numberofReview:290,coordinates:{lat:-26.1888612 , lng:28.246325},discount:10 , deliveryTime:45 , collectTime:5 , foodType:"Fish , Prawns , Pad See Ew , Sides , Drinks , Add on , Fries",
    productData:[{name:"Fish" , price:1500 , image:"https://previews.123rf.com/images/susansam/susansam1903/susansam190300075/121711821-healthy-meal-fried-fish.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Prawns" , price:1600 , image:"https://img.delicious.com.au/0c7YYzXP/del/2015/10/tiger-prawns-with-chermoula-butter-23662-1.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    
    {name:"Pad See Ew" , price:1200 , image:"https://www.foodandwine.com/thmb/4OiyQJDbzKuy-mUfOWLVho0bOWM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Pad-Se-Ew-FT-RECIPE0623-31e03aa47c9a4bb58d1da3a8ffb405b6.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Sides" , price:500 , image:"https://www.corriecooks.com/wp-content/uploads/2023/03/What-To-Serve-With-Chicken-Salad.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Drink" , price:200 , image:"https://mybartender.com/wp-content/uploads/2022/11/Tropical-Rum-Cocktails.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Add on" , price:1300 , image:"https://hips.hearstapps.com/hmg-prod/images/black-pepper-chicken2-1647635684.jpeg?crop=0.696xw:1.00xh;0.135xw,0&resize=640:*",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Fries" , price:400 , image:"https://d1e1vgxjd1htwd.cloudfront.net/-/media/recipe-asian-style-french-fries.jpg?h=775&la=en&w=1000&hash=F6EC39A66B26A0EBB4732C3F862DC8DF721C5BD6",productDetails:'Gluten-free, nutrient-rich ancient grain'},


],
    id:3,
    category:'ChineseFood'},

    {restaurantName:"Fuchsia Kitchen" , farAway:"34.2",
    businessAddress:"Building no 81,Street7" , images:'https://www.youlinmagazine.com/articles/fuchsia-kitchen-lahore-2.jpg',
    averageReview:4.3, numberofReview:220,coordinates:{lat:-26.1888612 , lng:28.246325},discount:10 , deliveryTime:45 , collectTime:5 , foodType:"Hoodles,Sweets,Rice&Vegetable,Beverages,Mocktails",
    productData:[{name:"Hoodles" , price:3000 , image:"https://shop.momofuku.com/cdn/shop/articles/Triple_Garlic_Chicken_Ramen_1_for_Website.jpg?v=1672862203",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Sweet" , price:900 , image:"https://media-cdn.tripadvisor.com/media/photo-s/19/50/d8/df/fuchsia-kitchen-meetup.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    
    {name:"Rice&Vegetable" , price:2000 , image:"https://fuchsiapk.com/images/img-01.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Beverage" , price:500 , image:"https://cdn.britannica.com/33/206333-050-598A0208/sodas-plastic-cups-ice-straws.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Mocktail" , price:700 , image:"https://suebeehomemaker.com/wp-content/uploads/2023/03/strawberry-mojito-mocktails-recipecard.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    


], id:4,
   category:'ChineseFood'},

{restaurantName:"Arcadian Cafe" , farAway:"38.2",
businessAddress:"28 K Gulberg 2" , images:'https://media-cdn.tripadvisor.com/media/photo-p/1a/2a/4f/f2/photo0jpg.jpg',
averageReview:4.7, numberofReview:290,coordinates:{lat:-26.1888612 , lng:28.246325},discount:50 , deliveryTime:45 , collectTime:5 , foodType:"Asian Fusion,French Italian,Dessert,Fusion Cuisine,Kids Menu, Side Order , Bar",
productData:[{name:"Asian Fusion" , price:4000 , image:"https://arcadiancafe.com/wp-content/uploads/2021/08/asianfusion-1.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
{name:"French Italian" , price:5000 , image:"https://arcadiancafe.com/wp-content/uploads/2021/08/continental.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},

{name:"Dessert" , price:1500 , image:"https://arcadiancafe.com/wp-content/uploads/2021/08/desserts.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
{name:"Fusion Cuisine" , price:2000 , image:"https://arcadiancafe.com/wp-content/uploads/2021/08/fusion-cuisine.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
{name:"Kids Menu" , price:700 , image:"https://arcadiancafe.com/wp-content/uploads/2021/08/kidsmenu.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
{name:"Side Order" , price:500 , image:"https://arcadiancafe.com/wp-content/uploads/2021/08/sideorders.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},

{name:"Bar" , price:700 , image:"https://arcadiancafe.com/wp-content/uploads/2021/08/straightfrombar.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},



], id:5,
   category:'ChineseFood'},

{restaurantName:"Waris Nihari" , farAway:"45.2",
businessAddress:"42 K Anarkali 2" , images:'https://foodnerd.s3.eu-west-1.amazonaws.com/production/blog/cover_image/1/foodnerd-islamabad_s-_desi-restaurants.jpg',
averageReview:3.9, numberofReview:420,coordinates:{lat:-26.1888612 , lng:28.246325},discount:20 , deliveryTime:45 , collectTime:5 , foodType:"Nihari,Fish,Tikka Boti , Kabab , Karahi, Roti",
productData:[{name:"Nihari" , price:550 , image:"https://swatisani.net/kitchen/wp-content/uploads/2015/12/IMG_9583.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
{name:"Fish" , price:500 , image:"https://img.freepik.com/free-photo/bottom-view-fish-fry-fried-eggplants-onion-peppers-wood-board-spices-small-bowls-fork-knife-tomatoes-oil-bottle-mint-dill-dark-background_140725-112096.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},

{name:"Tikka Boti" , price:400 , image:"https://tawaqqo.com/wp-content/uploads/2020/10/1-1.png",productDetails:'Gluten-free, nutrient-rich ancient grain'},
{name:"Kabab" , price:300 , image:"https://www.ndtv.com/cooks/images/seekh-kebab-620.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
{name:"Karahi" , price:900 , image:"https://rookiewithacookie.com/wp-content/uploads/2017/01/karahi-1024x720.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
{name:"Roti" , price:50 , image:"https://www.indianhealthyrecipes.com/wp-content/uploads/2023/09/tandoori-roti-recipe.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
], id:6,
   category:'NativeFood'},

    {restaurantName:"Dera Restaurant" , farAway:"50.2",
    businessAddress:"Hafeez Qardar Road" , images:'https://images.deliveryhero.io/image/fd-pk/LH/s5lt-hero.jpg?width=512&height=384&quality=45',
    averageReview:4.6 , numberofReview:210,coordinates:{lat:-26.1888612 , lng:28.246325},discount:25 , deliveryTime:45 , collectTime:5 , foodType:"chicken Karahi , Mutton Karahi , ColdDrinks , Beef Karahi",
    productData:[{name:"Chicken Karahi" , price:610 , image:"https://d2liqplnt17rh6.cloudfront.net/coverImages/Cover6_a6981387-76e7-4241-987a-f9fc051669b1-14.jpeg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Chicken Muglai" , price:650, image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmuXbi0KhztdlFrR57X4TR42rZ5xEjhW3H5Q&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Chicken Ginger" , price:600 , image:"https://www.budgetbytes.com/wp-content/uploads/2016/07/Dredge-Chicken-in-Glaze-Top-with-Garnish-1.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Mutton Karahi" , price:1200 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRa23SL1_3tu_NudlhM3Q1--ji4iPBikRFP-Q&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Daal Mash" , price:120 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq8e8YsXVfbJL5oUDkvVLseSBPAJujhu-Tcw&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Mix Vegetable" , price:120 , image:"https://www.secondrecipe.com/wp-content/uploads/2022/07/air-fryer-mixed-vegetables.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:7,
    category:'NativeFood'},

    {restaurantName:"Al-Rehman Biryani" , farAway:"41.7",
    businessAddress:"6B, 85-A, 1, Township" , images:'https://foodfusion.com/wp-content/uploads/2021/09/Al-Rehman-Biryani-Recipe-by-Food-fusion-1.jpg',
    averageReview:4.3 , numberofReview:234,coordinates:{lat:-26.1888612 , lng:28.246325},discount:75 , deliveryTime:45 , collectTime:5 , foodType:"Biryani , Zarda , Salad , Kheer , Raita",
    productData:[{name:"Biryani" , price:350 , image:"https://www.indianhealthyrecipes.com/wp-content/uploads/2023/02/paneer-biryani-recipe.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Zarda" , price:250, image:"https://shahzadidevje.com/wp-content/uploads/2019/05/zarda-NEW-blog-1x1.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Salad" , price:100 , image:"https://www.krumpli.co.uk/wp-content/uploads/2020/01/Kachumber-Salad-2.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Kheer" , price:200 , image:"https://www.cookwithmanali.com/wp-content/uploads/2017/06/Indian-Rice-Kheer-500x375.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Raita" , price:100 , image:"https://assets.bonappetit.com/photos/5914d07af2e50612b49acd21/16:9/w_1647,h_926,c_limit/cucumber-raita-with-black-mustard-and-cilantro.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:8,
    category:'NativeFood'},

    {restaurantName:"EI Momento" , farAway:"23.9",
    businessAddress:"Lahore MM Alam Road" , images:'https://media.istockphoto.com/id/632439546/photo/pasta-plate.jpg?s=612x612&w=0&k=20&c=zZPaNg_mf7cTVIeJPFVRtsjYClNYkGMcUc5ZBrARwZU=',
    averageReview:4.9 , numberofReview:150,coordinates:{lat:-26.1888612 , lng:28.246325},discount:15 , deliveryTime:45 , collectTime:5 , foodType:"Rattlesnake Pasta , Alfredo Pasta, Mushroom Pasta , Per Peila Cheese,House Spaghetti",
    productData:[{name:"Rattlesnake Pasta" , price:1450 , image:"https://cloudfront-us-east-1.images.arcpublishing.com/ajc/ONWN3DDEPVDPTDJKYZRUZOEEGQ.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Alfredo Pasta" , price:1495, image:"https://www.budgetbytes.com/wp-content/uploads/2017/07/Lighter-Spinach-Alfredo-Pasta-finished-500x500.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Mushroom Pasta" , price:1470 , image:"https://assets.bonappetit.com/photos/5d4ddd602c815a00080f9771/1:1/w_2560%2Cc_limit/BA-0919-Creamy-Pasta-Crispy-Mushroom-Playbook.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Per Peila Cheese" , price:1445 , image:"https://fussfreeflavours.com/wp-content/uploads/2021/02/Cream-cheese-pasta-featured-500x500.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"House Spaghetti" , price:1395 , image:"https://cdn.londonandpartners.com/asset/1d45b0801021c18b3d9c6f623b194678.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:9,
    category:'Pasta'},

    {restaurantName:"Pasta la Vista" , farAway:"27.9",
    businessAddress:" DHA Lahore" , images:'https://lh5.googleusercontent.com/LwsaOsj9tFs5HrwlhRh63T5DRfHPclw4vM7pRSoCjKyS5JYLZ2SAliL_4sMwD6O7-oORrd13OgRT959xQ38mbJPTve5WsrA6rKcjn8GGNOZxfd2MLJFNoiQGPYp_o77JBVS0ilpX-EyA-pfYcgYCvWY',
    averageReview:4.8 , numberofReview:198,coordinates:{lat:-26.1888612 , lng:28.246325},discount:5 , deliveryTime:45 , collectTime:5 , foodType:"Spaghetti,Linguine,Fettuccine,Penne,Spinach & Ricotta Ravioli",
    productData:[{name:"Spaghetti" , price:350 , image:"https://www.southernliving.com/thmb/-l60EsN2vZGyPIJ2UpSKdS2nCdk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/all-one-spaghetti-x_0_0_0-e93b5e6d14ea4d49a9dd4e53af490031-d4248ce8a65f4317b16c071ab0a2db97.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Linguine" , price:250, image:"https://images.immediate.co.uk/production/volatile/sites/30/2020/08/samphire-lemony-salmon-linguine-cb7be0d.jpg?quality=90&resize=500,454",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Fettuccine" , price:100 , image:"https://lh3.googleusercontent.com/-iYC5NnLWHy0xLBIGTfPzKQJgbfNo3-yzs_lqY2EpaV_WABGQvoItaXrF8C97UmundnfxMwmqIk6TnWlciiMdjNhaUO4hwH1AU6b=w1606-h1205-c-rj-v1-e365",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Penne" , price:200 , image:"https://www.kitchensanctuary.com/wp-content/uploads/2023/07/Penne-alarrabiata-square-FS.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Spinach & Ricotta Ravioli" , price:100 , image:"https://i.ndtvimg.com/i/2017-11/spinach-and-ricotta-ravioli-recipe_620x330_81509602670.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:10,
    category:'Pasta'},

    {restaurantName:"Tuscany Court Yard" , farAway:"23.9",
    businessAddress:"Lahore Johar Town" , images:'https://elmomento.pk/wp-content/uploads/2023/06/image-1.jpg',
    averageReview:4.1 , numberofReview:220,coordinates:{lat:-26.1888612 , lng:28.246325},discount:30 , deliveryTime:45 , collectTime:5 , foodType:"Fettuccine Alfredo Pasta,Spaghetti Bolognese Pasta , Chicken Lasagna , Marinara Pasta",
    productData:[{name:"Fettuccine Alfredo Pasta" , price:1500 , image:"https://www.savingdessert.com/wp-content/uploads/2019/05/Grilled-Chicken-Fettuccine-Alfredo-5.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Spaghetti Bolognese Pasta" , price:1450, image:"https://www.errenskitchen.com/wp-content/uploads/2018/08/Spaghetti-Bolognese-1-3.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Chicken Lasagna" , price:1500 , image:"https://www.sugardishme.com/wp-content/uploads/2019/10/Ground-Chicken-Lasagna-Square.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Marinara Pasta" , price:1600 , image:"https://www.sipandfeast.com/wp-content/uploads/2022/08/marinara-recipe-snippet.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:11,
    category:'Pasta'},

    {restaurantName:"Cosa Nostra" , farAway:"35.9",
    businessAddress:"Gulberg’s Cosa Nostra", images:'https://images.immediate.co.uk/production/volatile/sites/2/2021/06/hot-smoked-salmon-salad-6f16c73.jpg?quality=90&resize=556,505',
    averageReview:4.3 , numberofReview:350,coordinates:{lat:-26.1888612 , lng:28.246325},discount:20 , deliveryTime:45 , collectTime:5 , foodType:"Caesar Salad , Nicoise Salad,Tortilla Salad,Roasted Beet Salad",
    productData:[{name:"Caesar Salad" , price:1200 , image:"https://hips.hearstapps.com/hmg-prod/images/chicken-caesar-salad7-1654809005.jpg?crop=0.588xw:0.880xh;0.0497xw,0.120xh&resize=1200:*",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Nicoise Salad" , price:1000, image:"https://www.foodandwine.com/thmb/bkXN0Yi5YrBJzFx--W99t1V0AVs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Salade-Nicoise-FT-RECIPE0823-c7e3617cc7d4455f90a26fffa7ac128b.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Tortilla Salad" , price:1800 , image:"https://www.foodandwine.com/thmb/B3EcMX8q08taevIWgoJL6YUL4K8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/201401-r-xl-southwestern-tortilla-salad-jason-varney-ae9796d01d5245e69805e75d11cf630c.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Roasted Beet Salad" , price:1100 , image:"https://paleomg.com/wp-content/uploads/2018/04/EN0A2369-scaled.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:12,
    category:'Salad'},

    {restaurantName:"Bamboo Union" , farAway:"29.9",
    businessAddress:"Thokar Niaz Baig", images:'https://media.istockphoto.com/id/1264691515/photo/broccoli-cauliflower-salad.jpg?s=612x612&w=0&k=20&c=Q0edKb4H__NlLVt3XCM9nxNmFwddEJ0JQv5UoL2bAXA=',
    averageReview:4.9, numberofReview:420,coordinates:{lat:-26.1888612 , lng:28.246325},discount:15 , deliveryTime:45 , collectTime:5 , foodType:"Salmon Edamame Salad,Thai Beef Salad,Thai SeaFood Salad",
    productData:[{name:"Salmon Edamame Salad" , price:1500 , image:"https://i0.wp.com/bamboounion.pk/wp-content/uploads/2021/12/Salmon-Edamame-Salad.jpg?resize=300%2C300&ssl=1",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Thai Beef Salad" , price:1450, image:"https://i0.wp.com/bamboounion.pk/wp-content/uploads/2021/12/thai-beef-salad.jpg?resize=300%2C300&ssl=1",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Thai SeaFood Salad" , price:1500 , image:"https://i0.wp.com/bamboounion.pk/wp-content/uploads/2021/12/Grilled-Seafood-Salad-scaled-1.jpg?resize=300%2C300&ssl=1",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:13,
    category:'Salad'},

    {restaurantName:"Salad Bowl" , farAway:"18.9",
    businessAddress:"PIA Road Lahore" , images:'https://m.media-amazon.com/images/I/61aE26oS0-L._AC_UF350,350_QL80_.jpg',
    averageReview:4.1 , numberofReview:550,coordinates:{lat:-26.1888612 , lng:28.246325},discount:10 , deliveryTime:45 , collectTime:5 , foodType:"Chicken Caesar,Rancher,Asian Sensation,Salad Bowl Cobb",
    productData:[{name:"Chicken Caesar" , price:1500 , image:"https://healthyfitnessmeals.com/wp-content/uploads/2020/05/instagram-In-Stream_Square___Low-carb-Caesar-salad-4.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Rancher" , price:1450, image:"https://healthyfitnessmeals.com/wp-content/uploads/2019/05/Healthy-Ranch-chicken-salad.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Asian Sensation" , price:1500 , image:"https://www.southernkissed.com/wp-content/uploads/2021/04/Zensation-zalad-2.jpeg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Salad Bowl Cobb" , price:1600 , image:"https://i2.wp.com/hipfoodiemom.com/wp-content/uploads/2018/09/IMG_9184-1.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:14,
    category:'Salad'},

    {restaurantName:"Aslam Darul Mahi" , farAway:"23.9",
    businessAddress:"Johar Town, Lahore" , images:'https://mobile-cuisine.com/wp-content/uploads/2021/07/wp5116626.jpg',
    averageReview:4.9 , numberofReview:450,coordinates:{lat:-26.1888612 , lng:28.246325},discount:15 , deliveryTime:45 , collectTime:5 , foodType:"Abalone,Sea urchin,Crab,Tilapia",
    productData:[{name:"Abalone" , price:2500 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM2cOMMQmrXz-qGQX3DNM0cQYaZ68eMYG0oGaeI0Lb3wWPozNOGF07nEdOFlRTOUiMf4M&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:" Sea urchin" , price:2450, image:"https://www.foodrepublic.com/img/gallery/weird-or-good-sea-urchin-2/intro-import.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Crab" , price:2000 , image:"https://www.licious.in/blog/wp-content/uploads/2022/03/shutterstock_769889659-min-600x600.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Tilapia" , price:3000 , image:"https://i0.wp.com/images-prod.healthline.com/hlcmsresource/images/AN_images/tilapia-fish-meal-1296x728.jpg?w=1155&h=1528",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:15,
    category:'SeaFood'},

    {restaurantName:"Kinoko" , farAway:"12.2",
    businessAddress:"Lake City, Lahore" , images:'https://cdn.shopify.com/s/files/1/0588/8527/5820/files/Cajun_seafood_boil.jpg?v=1659014201',
    averageReview:4.2 , numberofReview:660,coordinates:{lat:-26.1888612 , lng:28.246325},discount:25 , deliveryTime:45 , collectTime:5 , foodType:"Lobster,Squid,Cat Fish,Salmon",
    productData:[{name:"Lobster" , price:1500 , image:"https://www.recipetineats.com/wp-content/uploads/2020/12/Lobster-Platter-1.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Squid" , price:1450, image:"https://ohsnapletseat.com/wp-content/uploads/2020/11/IMG_0220-1024x768.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Cat Fish" , price:1500 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2FjQfkbVt_vbzM_1ejtLgVazn_hBpaeTSrvXnqIRA6UI-KHjb-ZyiHOu97g2AvA1z6R4&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Salmon" , price:1600 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjuEpgx-hfxskJ-R8PMGoXyrhEy8gFtg6mPENW0LnVbNSDujTsQLagMy0diUbVPDE01GQ&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:16,
    category:'SeaFood'},

    {restaurantName:"Antique Cafe" , farAway:"20.3",
    businessAddress:"Emporium Mall, Lahore" , images:'https://6amcity.brightspotcdn.com/dims4/default/c2f6926/2147483647/strip/true/crop/1440x810+0+614/resize/1440x810!/quality/90/?url=https%3A%2F%2Fk1-prod-sixam-city.s3.us-east-2.amazonaws.com%2Fbrightspot%2F1c%2Ffc%2F3872897e4fb8887e75d623bccc09%2Fcajuncracknsj4.jpg',
    averageReview:4.5, numberofReview:234,coordinates:{lat:-26.1888612 , lng:28.246325},discount:40 , deliveryTime:45 , collectTime:5 , foodType:"Shrimp,Caviar,Sardines,Mussels",
    productData:[{name:"Shrimp" , price:2500 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMus39MteaGonqskbOOVhgRRvLKyP0TUlThQOy9WJR7axbDOAgTrKpAW_BTpCBF82vWqU&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Caviar" , price:2450, image:"https://cdn.shopify.com/s/files/1/0004/0825/6577/articles/easy.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Sardines" , price:3500 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvXmSar-ic8kIpdbAcFPlQbai_crP_iOg7exyMy4JfwVU2jGhtj1Pjf2gAv3IYsKCv5Io&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Mussels" , price:1600 , image:"https://www.foodandwine.com/thmb/xnsOoX7Y2eh00Xh-nta9O2rQM6E=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Sauvignon-Blanc-Steamed-Mussels-Garlic-Toasts-FT-RECIPE0822-2000-381984da6639497ca8da2339a727486d.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:17,
    category:'SeaFood'},

    {restaurantName:"Ali Baba Cafe" , farAway:"12.3",
    businessAddress:"Shop No G-6 Jinnah" , images:'https://static.vecteezy.com/system/resources/thumbnails/030/522/268/small/juice-and-healthy-fruits-photo.jpg',
    averageReview:4.9, numberofReview:78,coordinates:{lat:-26.1888612 , lng:28.246325},discount:20 , deliveryTime:45 , collectTime:5 , foodType:"Apple Juice, Blackberry Juice, Blueberry Juice,Cranberry Juice",
    productData:[{name:"Apple Juice" , price:500 , image:"https://www.alphafoodie.com/wp-content/uploads/2021/11/Apple-Juice-Square.jpeg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Blackberry Juice" , price:500, image:"https://www.organicfacts.net/wp-content/uploads/blackberryjuice.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Blueberry Juice" , price:500 , image:"https://vaya.in/recipes/wp-content/uploads/2018/05/Blueberry-Juice.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Cranberry Juice" , price:500 , image:"https://cdn-prod.medicalnewstoday.com/content/images/articles/322/322731/cranberry-juice-in-a-glass.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:18,
    category:'Juice'},

    {restaurantName:"Tayyab Juice" , farAway:"10.3",
    businessAddress:"Shop#5,Umer Hight" , images:'https://static.vecteezy.com/system/resources/thumbnails/022/454/679/small/mix-fruit-juice-in-a-glass-with-fresh-fruits-generative-ai-free-photo.jpg',
    averageReview:4.3, numberofReview:232,coordinates:{lat:-26.1888612 , lng:28.246325},discount:10 , deliveryTime:45 , collectTime:5 , foodType:"Grapefruit Juice,Grape Juice,Lemon Juice,Lime Juice",
    productData:[{name:"Grapefruit Juice" , price:600 , image:"https://www.verywellhealth.com/thmb/WHPCcBCxA6e4OTeVGKvR8xnotfQ=/1414x1414/smart/filters:no_upscale()/GettyImages-634466021-28eacdafbd674656a3651383f3ec2517.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Grape Juice" , price:400, image:"https://www.alphafoodie.com/wp-content/uploads/2022/03/How-to-Make-Grape-Juice-Square.jpeg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Lemon Juice" , price:300 , image:"https://bloximages.newyork1.vip.townnews.com/smithmountainlake.com/content/tncms/assets/v3/editorial/c/16/c168ca7c-27f4-50ec-83c7-70e08cdf77b5/649481cf4536c.image.jpg?crop=612%2C321%2C0%2C11&resize=612%2C321&order=crop%2Cresize",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Lime Juice" , price:300 , image:"https://www.alphafoodie.com/wp-content/uploads/2022/03/How-to-Make-Lime-Juice-Square.jpeg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:19,
    category:'Juice'},

    {restaurantName:"Hafiz Juice Bar" , farAway:"2.7",
    businessAddress:"Plaza 67,AA Comm" , images:'https://static.vecteezy.com/system/resources/thumbnails/029/824/369/small/assortment-of-fresh-fruit-juice-ai-generative-photo.jpg',
    averageReview:4.9, numberofReview:197,coordinates:{lat:-26.1888612 , lng:28.246325},discount:15 , deliveryTime:45 , collectTime:5 , foodType:"Orange Juice,Pineapple Juice,Pomegranate Juice,Prune Juice",
    productData:[{name:"Orange Juice" , price:300 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSflbFXdI6rxbGtGdMwUErZGuJvaigj-dfW2S3rBgWwFqgL2VNSNMQHtFxMkCMAfnGU13Q&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Pineapple Juice" , price:300, image:"https://cookathomemom.com/wp-content/uploads/2022/12/Pineapple-Ginger-Juice.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Pomegranate Juice" , price:300 , image:"https://extremewellnesssupply.com/cdn/shop/articles/7121e0bc570a942863e578951e9bba41_600x.jpg?v=1676283072",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Prune Juice" , price:300 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDnjM6UtsWbBfYof_zgfM0L2fq4oe8xS7W4mvu7jkDTW7Bo3Y9J7Rw9ni2ybkIBEeKwsc&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
],
    id:20,
    category:'Juice'},

    {restaurantName:"Baskin Robbins" , farAway:"23.4",
    businessAddress:"Roshaan Center 21-B" , images:'https://www.capitaland.com/content/dam/capitaland-tenants/imported/en/-/media/cma-malls/websites/logos_560/b/baskin%20robbins_baskin%20robbins%20560x462_805c9498-e4f1-41c6-a247-84eeb80c0cfc_560x462.jpg.transform/cap-lowres/image.jpg',
    averageReview:4.9, numberofReview:1020,coordinates:{lat:-26.1888612 , lng:28.246325},discount:25 , deliveryTime:45 , collectTime:5 , foodType:"Banana'N Strawberries,Black Currant, Fruit Overload, Litchi Gold,Cotton Candy",
    productData:[{name:"Banana'N Strawberries" , price:300 , image:"https://blog.profileplan.com/hubfs/Imported_Blog_Media/Strawberry-Banana-Ice-Cream.png",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Black Currant" , price:300, image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXtQnoUi7mW94TNTLqyczR6ggQX6Sd5_XI0eINKoSKtCiWjRhpGUBT0YMmYJwZCaD2wnw&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Fruit Overload" , price:300 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbEFXQWtfNw4xzJ9BFXDAZnVJLOgq_qa3fXQ&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Litchi Gold" , price:300 , image:"https://cdn-media.cure.fit/image/diy/d77a33ea-d6ef-4c34-8eec-55af497a9937",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Cotton Candy" , price:300 , image:"https://dessertsonadime.com/wp-content/uploads/2020/07/Cotton-Candy-Ice-Cream-set-2-Final-3-500x375.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},

],
    id:21,
    category:'IceCream'},

    {restaurantName:"Waffles by Waheed" , farAway:"21.2",
    businessAddress:"Johar Town, Lahore" , images:'https://d2liqplnt17rh6.cloudfront.net/coverImages/wafflescover_1c4ad284-5c4f-4906-8c7f-eba9900392f5-508.jpeg',
    averageReview:4.2, numberofReview:1200,coordinates:{lat:-26.1888612 , lng:28.246325},discount:35 , deliveryTime:45 , collectTime:5 , foodType:"Cones, Cups, Heavy Duty Treats, Delight Cups, Sundaes",
    productData:[{name:"Cone" , price:300 , image:"https://bakingamoment.com/wp-content/uploads/2018/09/IMG_9763-how-to-make-ice-cream-cone-cupcakes-square.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Cup" , price:300, image:"https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Heavy Duty Treat" , price:300 , image:"https://www.tasteofhome.com/wp-content/uploads/2021/05/FT20_207116_F_0206_1-horiz.jpg?fit=700%2C800",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Delight Cup" , price:300 , image:"https://m.media-amazon.com/images/I/81aS9uAGKJL._AC_UF350,350_QL80_.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Sundaes" , price:300 , image:"https://www.keep-calm-and-eat-ice-cream.com/wp-content/uploads/2022/08/Ice-cream-sundae-hero-11.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},

],
    id:22,
    category:'IceCream'},

    {restaurantName:"Sweet Factory-Lake City" , farAway:"34.5",
    businessAddress:"Lake City Mall" , images:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSghJmfChBeGZQpv4xwFjfTqGpbYUeQBDbcwtOO_GBWQm0aHSr2vBL8dYjhXlr7vxBarMk&usqp=CAU',
    averageReview:4.1, numberofReview:900,coordinates:{lat:-26.1888612 , lng:28.246325},discount:15 , deliveryTime:45 , collectTime:5 , foodType:"French Praline, Choco Fudge Brownie, Charcoal Detox, Caramel Crunch,Chocolate Orange",
    productData:[{name:"French Praline" , price:300 , image:"https://www.thespruceeats.com/thmb/JKNxqT-kLFW5Y2wgKkrB32uiWkU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/ButterPecanHERO-f53e544403794264b604167b4f8ff8ff.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Choco Fudge Brownie" , price:300, image:"https://getinspiredeveryday.com/wp-content/uploads/2020/08/Homemade-Chocolate-Fudge-Ice-Cream-Get-Inspired-Everyday-8.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Charcoal Detox" , price:300 , image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXPd11P0C5EwSfd3LYUGf6Rb7oiY5Qop3gl7pFHXzGYIbg17Aa-wgTgohnsJJZJGxRAwg&usqp=CAU",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Caramel Crunch" , price:300 , image:"https://hips.hearstapps.com/redonline/main/thumbs/735/1312297413-valentine-warner-rye-crispbread-and-caramel-crunch-ice-cream.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},
    {name:"Chocolate Orange" , price:300 , image:"https://empoweredsustenance.com/wp-content/uploads/2014/09/dark-chocolate-orange-ice-cream.jpg",productDetails:'Gluten-free, nutrient-rich ancient grain'},

],
    id:23,
    category:'IceCream'},
]

export const specialData=[
    {title:"AVAILABLE_ONLINE",key:0},
    {title:"FILLED_WITH_FLAVOUR",key:1},
    {title:"FRESHLY_PREPARED",key:2},
    {title:"DELIVERY_EXPERTS",key:3},
];

export const menuDetailedData =[
    { 
        preferenceTitle:["Choose your dips","Choose your 1st drink flavour", "Choose your 2nd drink flavour","Would you like to add a side?","Would you Like to add any snacks?"  ],
        preferenceData: [
  
          [{name:"Jalapeno Dip",price:8.91,checked:false,id:0},{name:"Sweet & Sour Dip",price:8.75,checked:false ,id:1},{name:'BBQ Dip',price:11.99 ,checked:false,id:2},
          ],
  
          [{name:"Small Coke",price:8.90 ,checked:false,id:3 },{name:"Small Fanta Orange",price:8.90 ,checked:false,id:4},{name:'Small Sprite',price:11.90,checked:false ,id:5},
          {name:'Small Coke Zero',price:3.95 ,checked:false,id:6},{name:'Small Syoney Zero',price:3.95 ,checked:false,id:7},{name:'Small Apple Juice',price:10.95 ,checked:false,id:8},
          {name:'Small Strawberry Shake',price:16.95 ,checked:false,id:9},{name:'Small Chocolate Shake',price:16.95 ,checked:false,id:10},
          ],
  
          [{name:"Small Coke",price:8.90,checked:false ,id:11},{name:"Small Fanta Orange",price:8.90,checked:false ,id:12},{name:'Small Sprite',price:11.90,checked:false ,id:13},
          {name:'Small Coke Zero',price:3.95 ,checked:false,id:14},{name:'Small Syoney Zero',price:3.95 ,checked:false,id:15},{name:'Small Apple Juice',price:10.95,checked:false ,id:16},
          {name:'Small Strawberry Shake',price:16.95,checked:false ,id:17},{name:'Small Chocolate Shake',price:16.95 ,checked:false,id:18},{name:'Small Vanilla Shake',price:17.95 ,checked:false,id:19},
            ],
              
          [{name:"debonairs sauce",price:8.90 ,checked:false,id:20},{name:"BBQ Sauce",price:8.90,checked:false ,id:21},{name:'Tikka Sauce',price:11.90,checked:false ,id:22},
          ],
  
          [
            {name: "Potato Chips", price: 5.99, checked: false, id: 23},
            {name: "Pretzels", price: 4.49, checked: false, id:24},
            {name: "Mixed Nuts", price: 7.99, checked: false, id: 25},
            {name: "Cheese Crackers", price: 6.99, checked: false, id: 26},
            {name: "Vegetable Sticks", price: 8.99, checked: false, id: 27},
            {name: "Popcorn", price: 3.99, checked: false, id: 28},
          ]
          
          ],
        
          minimum_quatity:[null,1,1,null,null],
          counter:[0,0,0,0,0],
          required: [false,true,true,false,false],  
    },
]
